//-- SECTION: CIRCUITS DATA --//
const CIRCUITS = [
  {
    id: "spa",
    name: "Circuit de Spa-Francorchamps",
    shortName: "Spa",
    country: "Belgium",
    city: "Stavelot",
    flag: "🇧🇪",
    region: "Europe",
    type: "High-Speed",
    length: 7.004,
    turns: 19,
    lapRecord: "1:46.286 - Bottas 2018",
    lat: 50.4372,
    lon: 5.9714,
    baseDownforce: "Medium-High",
    tyreWear: "Medium",
    brakingDemand: "Medium",
    surfaceGrip: "High",
    altitudeM: 401,
    description:
      "Spa rewards stable aerodynamic load through Eau Rouge, Raidillon, Pouhon, and Blanchimont while still demanding low drag on the Kemmel Straight. The large elevation change and changeable Ardennes weather make ride height, tyre temperature control, and brake migration especially sensitive.",
  },
  {
    id: "monza",
    name: "Autodromo Nazionale Monza",
    shortName: "Monza",
    country: "Italy",
    city: "Monza",
    flag: "🇮🇹",
    region: "Europe",
    type: "High-Speed",
    length: 5.793,
    turns: 11,
    lapRecord: "1:21.046 - Barrichello 2004",
    lat: 45.6156,
    lon: 9.2811,
    baseDownforce: "Low",
    tyreWear: "Low",
    brakingDemand: "High",
    surfaceGrip: "High",
    altitudeM: 162,
    description:
      "Monza is the benchmark low-downforce circuit, with long full-throttle sections broken by heavy braking zones and traction exits. Mechanical stability over kerbs matters because the fastest lap time comes from attacking the chicanes without compromising minimum drag.",
  },
  {
    id: "suzuka",
    name: "Suzuka Circuit",
    shortName: "Suzuka",
    country: "Japan",
    city: "Suzuka",
    flag: "🇯🇵",
    region: "Asia-Pacific",
    type: "Technical",
    length: 5.807,
    turns: 18,
    lapRecord: "1:30.983 - Hamilton 2019",
    lat: 34.8431,
    lon: 136.5407,
    baseDownforce: "Medium-High",
    tyreWear: "High",
    brakingDemand: "Medium",
    surfaceGrip: "High",
    altitudeM: 45,
    description:
      "Suzuka's figure-eight layout links sustained lateral load through the Esses, Degner, Spoon, and 130R, so aero balance must stay consistent across speed ranges. Tyre energy is high because corner sequences give the tyres very little recovery time before the next load spike.",
  },
  {
    id: "silverstone",
    name: "Silverstone Circuit",
    shortName: "Silverstone",
    country: "United Kingdom",
    city: "Silverstone",
    flag: "🇬🇧",
    region: "Europe",
    type: "High-Speed",
    length: 5.891,
    turns: 18,
    lapRecord: "1:27.097 - Verstappen 2020",
    lat: 52.0733,
    lon: -1.0147,
    baseDownforce: "Medium-High",
    tyreWear: "High",
    brakingDemand: "Medium",
    surfaceGrip: "High",
    altitudeM: 153,
    description:
      "Silverstone is dominated by high-speed lateral stability through Copse, Maggotts, Becketts, and Stowe. The setup window favors efficient downforce and controlled tyre surface temperatures because long loaded corners punish sliding.",
  },
  {
    id: "monaco",
    name: "Circuit de Monaco",
    shortName: "Monaco",
    country: "Monaco",
    city: "Monte Carlo",
    flag: "🇲🇨",
    region: "Europe",
    type: "Street Circuit",
    length: 3.337,
    turns: 19,
    lapRecord: "1:12.909 - Hamilton 2021",
    lat: 43.7347,
    lon: 7.4206,
    baseDownforce: "Very High",
    tyreWear: "Low",
    brakingDemand: "Medium",
    surfaceGrip: "Low",
    altitudeM: 8,
    description:
      "Monaco prioritizes maximum downforce, steering response, and traction rather than aerodynamic efficiency. The low-speed street layout has limited runoff and low grip evolution, so ride compliance and brake release stability are more valuable than straight-line speed.",
  },
  {
    id: "nurburgring-gp",
    name: "Nürburgring Grand Prix Circuit",
    shortName: "Nürburgring GP",
    country: "Germany",
    city: "Nürburg",
    flag: "🇩🇪",
    region: "Europe",
    type: "Hybrid",
    length: 5.148,
    turns: 15,
    lapRecord: "1:28.139 - Verstappen 2020",
    lat: 50.3356,
    lon: 6.9475,
    baseDownforce: "Medium-High",
    tyreWear: "Medium",
    brakingDemand: "High",
    surfaceGrip: "Medium",
    altitudeM: 620,
    description:
      "The Nürburgring GP layout mixes heavy braking, slow traction phases, and medium-speed direction changes, which makes brake balance and differential tuning central to lap time. Its higher altitude and cool Eifel conditions can reduce power and complicate tyre warmup.",
  },
  {
    id: "cota",
    name: "Circuit of The Americas",
    shortName: "COTA",
    country: "United States",
    city: "Austin",
    flag: "🇺🇸",
    region: "Americas",
    type: "Hybrid",
    length: 5.513,
    turns: 20,
    lapRecord: "1:36.169 - Leclerc 2019",
    lat: 30.1328,
    lon: -97.6411,
    baseDownforce: "Medium-High",
    tyreWear: "High",
    brakingDemand: "High",
    surfaceGrip: "Medium",
    altitudeM: 161,
    description:
      "COTA combines a steep uphill braking zone, fast esses, long straights, and slow technical corners, so the car needs a broad balance envelope. Tyre wear is driven by repeated lateral load and traction zones, especially when track temperatures rise in Austin.",
  },
  {
    id: "interlagos",
    name: "Autódromo José Carlos Pace",
    shortName: "Interlagos",
    country: "Brazil",
    city: "São Paulo",
    flag: "🇧🇷",
    region: "Americas",
    type: "Hybrid",
    length: 4.309,
    turns: 15,
    lapRecord: "1:10.540 - Bottas 2018",
    lat: -23.7036,
    lon: -46.6997,
    baseDownforce: "Medium-High",
    tyreWear: "Medium",
    brakingDemand: "Medium",
    surfaceGrip: "Medium",
    altitudeM: 760,
    description:
      "Interlagos is short but highly asymmetric, with elevation changes and a long full-throttle climb from Juncao to Turn 1. The higher altitude reduces engine output, while the infield requires rotation and traction that can conflict with straight-line efficiency.",
  },
  {
    id: "laguna-seca",
    name: "WeatherTech Raceway Laguna Seca",
    shortName: "Laguna Seca",
    country: "United States",
    city: "Monterey",
    flag: "🇺🇸",
    region: "Americas",
    type: "Technical",
    length: 3.602,
    turns: 11,
    lapRecord: "1:07.722 - Castroneves 2000",
    lat: 36.5843,
    lon: -121.7539,
    baseDownforce: "High",
    tyreWear: "Medium",
    brakingDemand: "Medium",
    surfaceGrip: "Medium",
    altitudeM: 250,
    description:
      "Laguna Seca is compact and technical, with blind crests and the Corkscrew forcing the setup to absorb rapid elevation change without losing platform control. Corner exit traction is critical because short straights leave little time to recover from wheelspin or under-rotation.",
  },
  {
    id: "bahrain",
    name: "Bahrain International Circuit",
    shortName: "Bahrain",
    country: "Bahrain",
    city: "Sakhir",
    flag: "🇧🇭",
    region: "Middle East",
    type: "Hybrid",
    length: 5.412,
    turns: 15,
    lapRecord: "1:31.447 - De la Rosa 2005",
    lat: 26.0325,
    lon: 50.5106,
    baseDownforce: "Medium",
    tyreWear: "High",
    brakingDemand: "High",
    surfaceGrip: "Medium",
    altitudeM: 7,
    description:
      "Bahrain places a premium on braking stability and rear traction because several long straights end in heavy stops followed by acceleration zones. Abrasive asphalt and hot ambient conditions make rear tyre degradation a primary setup constraint.",
  },
  {
    id: "yas-marina",
    name: "Yas Marina Circuit",
    shortName: "Yas Marina",
    country: "United Arab Emirates",
    city: "Abu Dhabi",
    flag: "🇦🇪",
    region: "Middle East",
    type: "Hybrid",
    length: 5.281,
    turns: 16,
    lapRecord: "1:26.103 - Verstappen 2021",
    lat: 24.4672,
    lon: 54.6031,
    baseDownforce: "Medium",
    tyreWear: "Medium",
    brakingDemand: "High",
    surfaceGrip: "High",
    altitudeM: 3,
    description:
      "Yas Marina's revised layout reduces stop-start drag but still requires strong braking performance and traction from low-speed exits. Twilight running changes track temperature during a stint, so setup choices must preserve balance as the circuit cools.",
  },
  {
    id: "red-bull-ring",
    name: "Red Bull Ring",
    shortName: "Red Bull Ring",
    country: "Austria",
    city: "Spielberg",
    flag: "🇦🇹",
    region: "Europe",
    type: "High-Speed",
    length: 4.318,
    turns: 10,
    lapRecord: "1:05.619 - Sainz 2020",
    lat: 47.2197,
    lon: 14.7647,
    baseDownforce: "Medium",
    tyreWear: "Medium",
    brakingDemand: "High",
    surfaceGrip: "High",
    altitudeM: 677,
    description:
      "The Red Bull Ring is short, fast, and altitude-sensitive, with big braking events compressed into the first half of the lap. Efficient aero and traction out of uphill corners are vital because lap time gaps are tiny and power loss from elevation is meaningful.",
  },
  {
    id: "barcelona-catalunya",
    name: "Circuit de Barcelona-Catalunya",
    shortName: "Barcelona",
    country: "Spain",
    city: "Montmeló",
    flag: "🇪🇸",
    region: "Europe",
    type: "Technical",
    length: 4.657,
    turns: 14,
    lapRecord: "1:16.330 - Verstappen 2023",
    lat: 41.57,
    lon: 2.2611,
    baseDownforce: "High",
    tyreWear: "High",
    brakingDemand: "Medium",
    surfaceGrip: "High",
    altitudeM: 109,
    description:
      "Barcelona is a reference circuit for aerodynamic balance because it combines long loaded corners, medium-speed direction changes, and traction exits. The left-front tyre is heavily stressed, so excessive understeer quickly becomes both a lap-time and degradation problem.",
  },
  {
    id: "hungaroring",
    name: "Hungaroring",
    shortName: "Hungaroring",
    country: "Hungary",
    city: "Mogyoród",
    flag: "🇭🇺",
    region: "Europe",
    type: "Technical",
    length: 4.381,
    turns: 14,
    lapRecord: "1:16.627 - Hamilton 2020",
    lat: 47.583,
    lon: 19.251,
    baseDownforce: "High",
    tyreWear: "Medium",
    brakingDemand: "Medium",
    surfaceGrip: "Medium",
    altitudeM: 238,
    description:
      "The Hungaroring is slow-to-medium speed and rhythm-heavy, so lap time comes from front-end response and controlled rotation through continuous corners. Limited straights mean cooling and traffic management can matter as much as peak power.",
  },
  {
    id: "imola",
    name: "Autodromo Internazionale Enzo e Dino Ferrari",
    shortName: "Imola",
    country: "Italy",
    city: "Imola",
    flag: "🇮🇹",
    region: "Europe",
    type: "Technical",
    length: 4.909,
    turns: 19,
    lapRecord: "1:15.484 - Hamilton 2020",
    lat: 44.3439,
    lon: 11.7167,
    baseDownforce: "Medium-High",
    tyreWear: "Medium",
    brakingDemand: "High",
    surfaceGrip: "Medium",
    altitudeM: 37,
    description:
      "Imola is narrow and old-school, with kerb usage, braking confidence, and traction over elevation changes defining performance. The car must be compliant enough for Variante Alta and Acque Minerali while retaining aero stability through faster sections.",
  },
  {
    id: "paul-ricard",
    name: "Circuit Paul Ricard",
    shortName: "Paul Ricard",
    country: "France",
    city: "Le Castellet",
    flag: "🇫🇷",
    region: "Europe",
    type: "Hybrid",
    length: 5.842,
    turns: 15,
    lapRecord: "1:32.740 - Vettel 2019",
    lat: 43.2506,
    lon: 5.7917,
    baseDownforce: "Medium",
    tyreWear: "Medium",
    brakingDemand: "Medium",
    surfaceGrip: "High",
    altitudeM: 408,
    description:
      "Paul Ricard has long straights, flat-radius corners, and high-grip runoff surfaces that encourage precise aero efficiency tuning. The Mistral Straight rewards low drag, but the final sector still needs enough front load to protect minimum speed.",
  },
  {
    id: "zandvoort",
    name: "Circuit Zandvoort",
    shortName: "Zandvoort",
    country: "Netherlands",
    city: "Zandvoort",
    flag: "🇳🇱",
    region: "Europe",
    type: "Technical",
    length: 4.259,
    turns: 14,
    lapRecord: "1:11.097 - Hamilton 2021",
    lat: 52.3888,
    lon: 4.5409,
    baseDownforce: "High",
    tyreWear: "High",
    brakingDemand: "Medium",
    surfaceGrip: "High",
    altitudeM: 6,
    description:
      "Zandvoort's banked corners and flowing middle sector require a stable aero platform under combined steering and compression loads. The coastal setting can bring wind shifts, making front-end confidence and tyre temperature control difficult to maintain.",
  },
  {
    id: "sepang",
    name: "Sepang International Circuit",
    shortName: "Sepang",
    country: "Malaysia",
    city: "Sepang",
    flag: "🇲🇾",
    region: "Asia-Pacific",
    type: "Hybrid",
    length: 5.543,
    turns: 15,
    lapRecord: "1:34.080 - Vettel 2017",
    lat: 2.7608,
    lon: 101.7381,
    baseDownforce: "Medium",
    tyreWear: "High",
    brakingDemand: "High",
    surfaceGrip: "Medium",
    altitudeM: 40,
    description:
      "Sepang combines two long straights with wide, technical corner complexes that reward balanced aero rather than a single extreme setup direction. Heat and humidity increase cooling demand and can push tyres into thermal degradation during long stints.",
  },
  {
    id: "marina-bay",
    name: "Marina Bay Street Circuit",
    shortName: "Marina Bay",
    country: "Singapore",
    city: "Singapore",
    flag: "🇸🇬",
    region: "Asia-Pacific",
    type: "Street Circuit",
    length: 4.94,
    turns: 19,
    lapRecord: "1:35.867 - Hamilton 2023",
    lat: 1.2914,
    lon: 103.864,
    baseDownforce: "High",
    tyreWear: "Medium",
    brakingDemand: "Very High",
    surfaceGrip: "Medium",
    altitudeM: 5,
    description:
      "Marina Bay is a high-downforce street circuit where braking, traction, and thermal management dominate over peak aerodynamic efficiency. Night running lowers ambient conditions slightly, but humidity and repeated braking zones keep cooling margins tight.",
  },
  {
    id: "hermanos-rodriguez",
    name: "Autódromo Hermanos Rodríguez",
    shortName: "Hermanos Rodríguez",
    country: "Mexico",
    city: "Mexico City",
    flag: "🇲🇽",
    region: "Americas",
    type: "Hybrid",
    length: 4.304,
    turns: 17,
    lapRecord: "1:17.774 - Bottas 2021",
    lat: 19.4042,
    lon: -99.0907,
    baseDownforce: "High",
    tyreWear: "Medium",
    brakingDemand: "High",
    surfaceGrip: "Medium",
    altitudeM: 2285,
    description:
      "Mexico City's extreme altitude reduces air density, so teams run high wing angles while still producing lower effective downforce than expected. Power unit cooling, turbo response, and braking stability are central because the long straight leads into major stops.",
  },
];

class CircuitDirectory {
  static getById(id) {
    return CIRCUITS.find((circuit) => circuit.id === id) || null;
  }

  static search(query) {
    const normalizedQuery = String(query || "")
      .trim()
      .toLowerCase();

    if (!normalizedQuery) {
      return CIRCUITS;
    }

    return CIRCUITS.filter((circuit) => {
      const searchableFields = [
        circuit.name,
        circuit.shortName,
        circuit.country,
        circuit.city,
      ];

      return searchableFields.some((field) =>
        field.toLowerCase().includes(normalizedQuery),
      );
    });
  }

  static filterByType(type) {
    const normalizedType = String(type || "all")
      .trim()
      .toLowerCase();

    if (normalizedType === "all") {
      return CIRCUITS;
    }

    return CIRCUITS.filter(
      (circuit) => circuit.type.toLowerCase() === normalizedType,
    );
  }
}

window.CIRCUITS = CIRCUITS;
window.getCircuitById = (id) => CircuitDirectory.getById(id);
window.searchCircuits = (query) => CircuitDirectory.search(query);
window.filterCircuitsByType = (type) => CircuitDirectory.filterByType(type);
