/* ============================================================
   APEXSTRATEGY — HANDBOOK DATA
   ES6 module. Every handbook chapter is data, not hand-written
   HTML — HandbookController loops over these arrays to build the
   panes. Add a glossary entry / compound / track type here and it
   appears in the page automatically.
   ============================================================ */

/*-- SECTION: CHAPTER 1 — TERMINOLOGY GLOSSARY --*/

export const GLOSSARY = [
  {
    term: "Ambient Temperature",
    def: "The air temperature measured at track level, typically 1.5m above the asphalt surface. Ambient temperature directly influences tyre compound behaviour by controlling the rate of thermal energy transfer from the track surface into the tyre carcass: colder air slows warm-up, requiring softer compounds or extended heat cycles. It also determines air density, which affects aerodynamic downforce generation and engine intake charge, with lower temperatures producing denser air and marginally more power at equal throttle position.",
  },
  {
    term: "Track Temperature",
    def: "The surface temperature of the racing circuit asphalt, measured at the contact layer. It is typically 10-30°C higher than ambient depending on solar radiation, cloud cover, and the thermal conductivity of the surface compound. Track temperature is the primary determinant of tyre operating window: a surface below 15°C prevents soft compounds reaching working temperature, while above 50°C risks thermal degradation even on hard compounds. Street circuits on concrete surfaces heat more slowly than permanent asphalt facilities due to concrete's lower thermal conductivity.",
  },
  {
    term: "Tyre Degradation",
    def: "The progressive physical breakdown of the tyre compound's contact surface through mechanical abrasion, thermal overload, and chemical decomposition of the rubber polymer chains. Degradation occurs in three phases: surface grain loss (minor performance drop), blistering (gas pockets forming inside the compound, causing sudden grip loss), and structural delamination (catastrophic failure). Engineers distinguish between \"deg\", the linear performance loss manageable within a stint, and \"cliff\", the abrupt grip drop when thermal thresholds are breached.",
  },
  {
    term: "Air Density",
    def: "The mass of air per unit volume, governed primarily by altitude, temperature, and humidity. At higher altitudes such as Mexico City (2,285m), air density is approximately 24% lower than sea level, reducing aerodynamic downforce by the same proportion because lift and drag forces scale with density. Lower air density also reduces the mass flow through engine intake systems, affecting combustion efficiency and requiring adjusted fuel mixture maps. Teams pre-calculate altitude correction factors for wing angles and ERS deployment profiles before each event.",
  },
  {
    term: "Understeer",
    def: "A handling condition where the front tyres reach their lateral force limit before the rears, causing the car to follow a wider radius than the driver intends: the front end \"washes out\" toward the outside of the corner. Understeer typically results from excessive front tyre temperature, insufficient front downforce, excessive entry speed, or a centre of gravity biased too far rearward. Engineers address it by increasing front wing angle, adjusting front tyre camber toward negative, or transferring aerodynamic balance toward the front axle.",
  },
  {
    term: "Oversteer",
    def: "A handling condition where the rear tyres saturate before the fronts, causing the rear of the car to step outward in rotation: the car turns more sharply than intended, with the tail attempting to overtake the nose. Oversteer is often faster in raw lap time terms if the driver can exploit the rotation, but it dramatically accelerates rear tyre wear and can become unmanageable under high-energy inputs. Engineers balance it via rear wing angle, rear tyre pressure, and differential settings that control the locking ramp behaviour under power application.",
  },
  {
    term: "Downforce",
    def: "An aerodynamic force acting perpendicular to the direction of travel, pressing the car toward the road surface and increasing the normal load on all four tyres. Increased normal load raises the maximum lateral force a tyre can generate, enabling higher cornering speeds. Downforce is generated primarily by front and rear wings, the floor and diffuser system, and bodywork-directed airflow. The fundamental compromise in car design is that downforce always accompanies drag, the aerodynamic resistance to forward motion, requiring circuit-specific optimisation of the drag-to-downforce ratio.",
  },
  {
    term: "Drag",
    def: "Aerodynamic resistance opposing the car's forward motion, generated by pressure differential between the front and rear of the car and by skin friction across all surfaces. Drag scales with the square of velocity, making it disproportionately costly at high speeds: at 300km/h, aerodynamic drag represents over 80% of the total resistance the engine must overcome. At low-drag circuits like Monza, teams minimise wing angles to reduce drag even at the cost of downforce, accepting understeer through slow corners to gain critical tenths on the extended straights.",
  },
  {
    term: "Setup Window",
    def: "The range of suspension, aerodynamic, and mechanical configurations within which the car produces competitive and consistent lap times. A wide setup window means the car tolerates a broad range of settings without major performance degradation, which is preferred for variable conditions and driver adaptation. A narrow window means small deviations in tyre temperature, fuel load, or wing angle produce disproportionate lap time loss. Modern Formula 1 cars are designed with intentionally narrow setup windows to extract maximum performance, at the cost of requiring precise circuit-specific optimisation.",
  },
  {
    term: "Balance",
    def: "The distribution of aerodynamic and mechanical grip between the front and rear axles, expressed as a proportion of total downforce or as a centre-of-pressure position. A car is said to have \"front balance\" when more load acts through the fronts (producing tighter turn-in) and \"rear balance\" when the rears are loaded more heavily (producing stability under traction). Race engineers adjust balance dynamically through front wing angle, brake bias, and differential settings. The target balance shifts as fuel burns off across a stint because the centre of gravity moves as the tank empties.",
  },
  {
    term: "Camber",
    def: "The angle of the wheel relative to the vertical plane when viewed from the front or rear of the car, measured in degrees. Negative camber (top of tyre leaning inward toward the car) increases the contact patch under lateral load by counteracting the tyre's natural tendency to roll onto its outer shoulder during cornering. Modern racing slicks run 3-5° of negative camber on the front axle to optimise the contact patch through high-speed corners, but excessive negative camber causes accelerated wear on the inner shoulder under straight-line and braking conditions.",
  },
  {
    term: "Toe Angle",
    def: "The inward or outward angle of the wheels relative to the car's centreline when viewed from above, measured in millimetres of toe-in or toe-out. Front toe-out improves turn-in response by pre-rotating the outer front wheel toward the corner, but increases straight-line drag and tyre scrub. Rear toe-in increases straight-line stability and reduces the tendency for the rear to step out under power, at the cost of slightly reduced rotation. Engineers typically run front toe-out and rear toe-in, with magnitudes tuned per circuit based on the relative importance of stability versus agility.",
  },
];

/*-- SECTION: CHAPTER 2 — TYRE COMPOUNDS --*/
// accent = Pirelli sidewall colour · ratings drive the bar widths.

export const COMPOUNDS = [
  {
    name: "C1 · Hard",
    accent: "#e8e8e8",
    temp: "Optimal range: 35-55°C track",
    ratings: [
      { label: "Durability", value: "10", pct: 100, color: "#e8e8e8" },
      { label: "Performance", value: "3", pct: 30, color: "var(--accent)" },
    ],
    desc: "The hardest and most durable compound in the dry range, designed for circuits with high abrasion surfaces or extreme track temperatures. C1 generates peak grip only after extensive thermal build-up, making out-laps critical: engineers specify careful sector-by-sector energy input on formation and safety-car laps to avoid running the first competitive lap cold.",
  },
  {
    name: "C2 · Medium",
    accent: "#f5c842",
    temp: "Optimal range: 25-45°C track",
    ratings: [
      { label: "Durability", value: "7", pct: 70, color: "#f5c842" },
      { label: "Performance", value: "5", pct: 50, color: "var(--accent)" },
    ],
    desc: "The medium offers a balance between pace and longevity, typically serving as the primary race compound at circuits with moderate tyre loading. It is frequently the pivot compound in two-stop strategies, used for the first stint to manage early race traffic before transitioning to a faster compound once track position is established.",
  },
  {
    name: "C3 · Soft",
    accent: "#e8611a",
    temp: "Optimal range: 15-35°C track",
    ratings: [
      { label: "Durability", value: "4", pct: 40, color: "#e8611a" },
      { label: "Performance", value: "7.5", pct: 75, color: "var(--accent)" },
    ],
    desc: "The primary qualifying compound under cool to moderate track temperatures, C3 reaches operating temperature within one to two laps and generates the highest peak grip of the dry-weather range. Its short operating window means engineers closely monitor tread surface temperature every lap, typically planning stints of 10-18 laps before degradation becomes a pace liability.",
  },
  {
    name: "C4 · Super Soft",
    accent: "#cc1a1a",
    temp: "Optimal range: 10-28°C track",
    ratings: [
      { label: "Durability", value: "2", pct: 22, color: "#cc1a1a" },
      { label: "Performance", value: "9", pct: 88, color: "var(--accent)" },
    ],
    desc: "Deployed at cold or low-abrasion circuits where generating heat into the tyre is the primary engineering challenge. C4 provides exceptional immediate grip but reaches its thermal limit rapidly under sustained loading, making it primarily a qualifying-focused compound or a short final-stint weapon in strategic split scenarios.",
  },
  {
    name: "C5 · Ultra Soft",
    accent: "#8b0000",
    temp: "Optimal range: 5-22°C track",
    ratings: [
      { label: "Durability", value: "1", pct: 10, color: "#8b0000" },
      { label: "Performance", value: "10", pct: 100, color: "var(--accent)" },
    ],
    desc: "The softest compound in the Pirelli range, reserved for extreme cold or street circuits where grip generation from track rubber is minimal. C5 can degrade to the point of structural blistering within a single high-load lap under hot track conditions. Its use in race conditions is rare and typically defensive, deployed by a car that needs to build a large enough gap to survive a single aggressive stint.",
  },
  {
    name: "Intermediate",
    accent: "#1a8a3a",
    temp: "Water film: 0.5-3mm · drying or light rain",
    ratings: [
      { label: "Wet perf.", value: "6.5", pct: 65, color: "#1a8a3a" },
      { label: "Dry perf.", value: "3.5", pct: 35, color: "var(--accent)" },
    ],
    desc: "The crossover compound, designed for a drying track or light rain where the full wet is too aggressive and dry slicks cannot generate sufficient temperature. The intermediate's tread pattern channels water away from the contact patch while retaining enough slick area for thermal stability. The transition window to slick tyres is the most strategically critical decision in any wet race, typically timed 2-3 laps after the driver reports consistent warmth across all four tyres.",
  },
  {
    name: "Full Wet",
    accent: "#1a4488",
    temp: "Water film: 3mm+ · active rain",
    ratings: [
      { label: "Wet perf.", value: "10", pct: 100, color: "#1a4488" },
      { label: "Dry perf.", value: "1", pct: 10, color: "var(--accent)" },
    ],
    desc: "The only compound rated for standing water and heavy rain, with deep circumferential grooves displacing up to 65 litres of water per second at race speed. Full wet tyres overheat extremely rapidly on a drying surface: running them 2-3 laps after conditions are intermediate produces surface temperatures that delaminate the tread structure within minutes. Race control typically declares an intermediate threshold at approximately 3mm/hour rainfall rate.",
  },
];

/*-- SECTION: CHAPTER 3 — AERODYNAMICS --*/
// `angles` (optional) renders rec-block cards under the section body.

export const AERO_SECTIONS = [
  {
    title: "The Front Wing",
    body: "The front wing is a multi-element cascade of aerofoil sections spanning the full width of the car ahead of the front axle. Its primary function is dual: generating downforce on the front axle to establish the car's aerodynamic balance, and conditioning the airflow entering the car's floor, bargeboard region, and sidepods. Because the front wing operates in ground effect, its downforce generation is highly sensitive to ride height: a 5mm increase in front ride height reduces front downforce by as much as 8% on modern cars, making spring rates and heave damping critical aerodynamic parameters as well as mechanical ones.",
    angles: [
      {
        level: "optimal",
        title: "Low angle (2-4°)",
        value: "LOW-DRAG CIRCUITS",
        reason:
          "Monza, Red Bull Ring, Spa back straight. Minimum viable downforce for front-end stability. Accepts moderate understeer through slow corners in exchange for maximum straight-line speed.",
      },
      {
        level: "warning",
        title: "Medium angle (6-10°)",
        value: "BALANCED CIRCUITS",
        reason:
          "Silverstone, Barcelona, COTA. Balanced compromise between cornering performance and straight-line efficiency. The most common starting point for setup development.",
      },
      {
        level: "critical",
        title: "High angle (12-16°)",
        value: "HIGH-DOWNFORCE CIRCUITS",
        reason:
          "Monaco, Singapore, Hungary. Maximum front downforce for slow-corner rotation and aggressive trail-braking. Acceptable drag penalty when no long straights exist.",
      },
    ],
  },
  {
    title: "The Rear Wing & DRS",
    body: "The rear wing operates in undisturbed freestream air well behind the car body and is the primary downforce-generating element on the rear axle. Unlike the front wing, it is not aerodynamically coupled to the floor's performance: changes to rear wing angle alter rear downforce and drag independently. The rear wing's most significant design constraint is that increasing downforce always increases drag, directly opposing the engine on the following straight. The Drag Reduction System (DRS) partially resolves this by allowing the driver to open a 50-75mm slot in the rear wing's main plane on designated straights, reducing drag by approximately 10-13 drag counts and adding 12-20km/h of top speed, sufficient to enable passing manoeuvres in most conditions.",
  },
  {
    title: "Floor, Diffuser & Ground Effect",
    body: "The floor of the car, the large sculpted underside surface between the front and rear axles, generates downforce through the Venturi principle: as air accelerates through the narrowing channel between the floor and road surface, its pressure drops, creating suction that pulls the car downward. The diffuser at the rear of the floor decelerates and expands this high-velocity underfloor air, recovering pressure cleanly and extracting maximum downforce. Modern ground-effect floors generate 40-60% of a car's total downforce with far lower drag than equivalent wing-generated downforce, making ride height management critical: a 1mm reduction in rear ride height can add 15-20 points of downforce at high speed, but risks catastrophic porpoising (aerodynamic stall) if the floor runs too close to the ground. Engineers target a minimum ride height that exploits ground effect without triggering stall, verified through simulation and floor rake sensor data during free practice sessions.",
  },
];

/*-- SECTION: CHAPTER 4 — TRACK TYPES --*/
// color = CSS var for the type name · badge = the type-* class suffix.

export const TRACK_TYPES = [
  {
    name: "Technical",
    color: "var(--accent-technical)",
    badge: "type-technical",
    typeLabel: "Type 1",
    examples: "Monaco · Hungaroring · Singapore · Imola",
    desc: "Dominated by slow to medium-speed corners, multiple direction changes, and limited opportunity for sustained high-speed running. Mechanical grip, delivered by suspension geometry, tyre contact patch, and differential calibration, outweighs aerodynamic grip in lap time contribution. Drivers spend a high proportion of each lap at partial throttle, making traction out of corners the dominant performance variable. Circuits in this category reward precise turn-in, progressive rotation through the apex, and aggressive early power application without spinning.",
    priorities: [
      "Maximum downforce configuration",
      "High mechanical grip (soft springs, low ride height)",
      "Aggressive differential ramp for traction",
      "Very soft compound (C3/C4)",
      "Brake bias toward rear for rotation",
    ],
  },
  {
    name: "High-Speed",
    color: "var(--accent-highspeed)",
    badge: "type-highspeed",
    typeLabel: "Type 2",
    examples: "Monza · Red Bull Ring · Silverstone · Paul Ricard",
    desc: "Characterised by sustained high-speed sections where aerodynamic forces dominate chassis balance. Top speeds exceed 330km/h at the most extreme examples, with the car spending 70-85% of the lap at full or near-full throttle. Low drag trim is essential, accepting moderate understeer through medium-speed sections as the cost of competitive straight-line velocity. High-speed stability, the car's resistance to aerodynamic pitching and yawing at 300km/h, requires careful suspension tuning, as oscillations at speed generate tyre temperature spikes that compress the setup window.",
    priorities: [
      "Low drag / low downforce wing trim",
      "Stiff suspension for aerodynamic stability",
      "DRS maximisation across available zones",
      "Hard compound (C1/C2) for thermal management",
      "Front brake cooling maximised (heavy braking zones)",
    ],
  },
  {
    name: "Street Circuit",
    color: "var(--accent-street)",
    badge: "type-street",
    typeLabel: "Type 3",
    examples: "Monaco · Singapore · Marina Bay",
    desc: "Temporary racing circuits laid on public road infrastructure, characterised by narrow track widths (typically 8-10m), concrete barrier walls with zero run-off, significant surface imperfections from road camber and manhole covers, and limited rubber accumulation at the start of a race weekend. The absence of a conventional overtaking opportunity means qualifying position determines race outcome at most street venues, placing exceptional value on single-lap performance. Surface grip builds rapidly across the weekend as tyre rubber deposits on the line, making late-session setups increasingly relevant.",
    priorities: [
      "Maximum downforce: the circuit cannot tolerate aero instability",
      "High ride height (surface irregularities)",
      "Progressive brake modulation (late braking zones)",
      "Very soft compound (C3-C5)",
      "Qualifying pace priority over race degradation",
    ],
  },
  {
    name: "Hybrid",
    color: "var(--text-secondary)",
    badge: "type-hybrid",
    typeLabel: "Type 4",
    examples: "Spa · Suzuka · COTA · Interlagos",
    desc: "The most demanding classification for car and tyre setup, hybrid circuits combine genuinely high-speed sections, where minimum downforce is preferred, with technical complexes where maximum mechanical grip is needed. Engineers cannot fully optimise for either extreme and instead seek a compromise configuration that performs acceptably across the full circuit. A classic example is Spa-Francorchamps: the low-drag requirement for Kemmel straight directly conflicts with the downforce needed for sustained high-lateral-load corners at Pouhon and the Bus Stop chicane. This compromise nature also makes hybrid circuits the most sensitive to weather changes, as rain shifts the optimal balance dramatically toward maximum downforce.",
    priorities: [
      "Balanced medium-high downforce compromise",
      "Flexible differential maps for varied corners",
      "Medium compound (C2/C3) for range coverage",
      "Tyre thermal management across all four corners",
      "Setup validated across the full lap, not a single sector",
    ],
  },
];

/*-- SECTION: CHAPTER REGISTRY --*/
// One row per handbook tab. HandbookController builds the tab button
// and pane for each, in order.

export const HANDBOOK_CHAPTERS = [
  { id: "terminology", label: "Terminology", render: "glossary" },
  { id: "compounds", label: "Tyre Compounds", render: "compounds" },
  { id: "aero", label: "Aerodynamics", render: "aero" },
  { id: "tracks", label: "Track Types", render: "tracks" },
];
